### ISSUE TITLE
Disable minification publish .min.js

### ISSUE THREAD

**Issue by CelegaS** [IgorTimoshenko/IMTYiiAssetic#4]
We actually use your AsseticScript, with Yii 1.1.x

The problem is I am publishing a folder containing some .js and some .min.js. And i have an error from JSMin.php because it try to minify a .min.js.

I want to know if it's possible to skip .min.js ?

Thanks,

**Comment by ihortymoshenko** [comment]
@CelegaS, there is no the ability to skip some files. If you need this, feel free to contribute ;)
